version: '1.1'

config:
  acme.sh:
    account_email:
    debug: false
#    default_dns_challenge: "--dns --yes-I-know-dns-manual-mode-enough-go-ahead-please"
    default_dns_challenge:
    dns_renew: true
    enabled: true
    force: false
    keylength: 4096
    keylength-ec: ec-384
    staging: false
  data-dir: './data'
  docker:
    prefix: mp_
  log-dir: './log'
  timezone: "Europe/Luxembourg"
  verbosity_level: 1

domains:
  - domain: 'example.com'
    mail: 'imap'
    smtp: 'smtp'
  - domain: 'example.org'
  - domain: 'example.net'

services:
  antivirus:
    enabled: true
  database:
    internal: true
  fail2ban:
    enabled: true
  mail:
    opendkim:
      debug: true
      enabled: true
    opendmarc:
      debug: true
      enabled: true
    spf:
      debug: true
      enabled: true
  web_services:
    phpmyadmin:
      debug: true
      enabled: true
      host: 'pma'
    postfixadmin:
      debug: true
      enabled: true
      host: 'pa'
    roundcubemail:
      debug: true
      enabled: true
      host: 'mail'
