version: '1.1'

config:
  acme.sh:
    account_email:
    debug: false
#    default_dns_challenge: "--dns --yes-I-know-dns-manual-mode-enough-go-ahead-please"
    default_dns_challenge:
    dns_renew: true
    enabled: true
    force: false
    keylength: '4096'
    keylength-ec: 'ec-384'
    staging: false
  docker:
    prefix: mp_
  folders:
    backup: "./backup"
    data: "./data"
    extra: "./extra"
    log: "./log"
  timezone: "Europe/Luxembourg"
  verbosity_level: 0

domains:
  - domain: 'example.com'
    mail: 'imap'
    smtp: 'smtp'
  - domain: 'example.org'
  - domain: 'example.net'

extra_domains: []

services:
  antivirus:
    enabled: true
  database:
    internal: true
  fail2ban:
    enabled: true
  mail:
    opendkim:
      debug: true
      enabled: true
    opendmarc:
      debug: true
      enabled: true
    spf:
      debug: true
      enabled: true
  web_services:
    phpmyadmin:
      debug: true
      enabled: true
      host: 'pma'
    postfixadmin:
      debug: true
      enabled: true
      host: 'pa'
    roundcubemail:
      debug: true
      enabled: true
      host: 'mail'
